export interface Tienda {
  pais: string;
  provincia: string;
  ciudad: string;
  nombre: string;
  direccion: string;
  telefono?: string;
  whatsapp?: string;
  web?: string;
  urlProbioticos?: string;
  horarios?: string;
  tiposProbioticos: string[];
  marcas?: string[];
  precioReferencia?: string;
  metodosPago?: string[];
  ventaOnline: boolean;
  fuente: string;
  fechaVerificacion: string;
  confiabilidad: 'Alta' | 'Muy Alta' | 'Media';
}

export const tiendasData: Tienda[] = [
  // España
  {
    pais: 'España',
    provincia: 'Comunidad de Madrid',
    ciudad: 'Madrid',
    nombre: 'Herbolario Navarro - Fuencarral',
    direccion: 'C/ Fuencarral, 138, 28010 Madrid',
    telefono: '916 227 932',
    web: 'https://www.herbolarionavarro.es/',
    urlProbioticos: 'https://www.herbolarionavarro.es/suplementos-probioticos-y-prebioticos',
    horarios: 'L-V: 9:00-21:00; S: 10:00-21:00; D y Festivos: 11:30-20:30',
    tiposProbioticos: ['Cápsulas', 'Sobres', 'Comprimidos'],
    marcas: ['Terra Verda', 'Natures Plus', 'Tongil', 'Nutergia', 'SuraVitasan', 'Bromatech'],
    precioReferencia: 'Megaflora en Sobres (14 uds): €13,99',
    metodosPago: ['Tarjeta de crédito', 'PayPal', 'Transferencia bancaria', 'Bizum'],
    ventaOnline: true,
    fuente: 'Web oficial 1',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'España',
    provincia: 'Comunidad de Madrid',
    ciudad: 'Madrid',
    nombre: 'Ecocentro',
    direccion: 'C/ Esquilache, 2-12, 28003 Madrid',
    telefono: '915 535 502',
    whatsapp: '690 334 737',
    web: 'https://www.ecocentro.es/',
    urlProbioticos: 'https://www.ecocentro.es/tienda/',
    horarios: 'Tienda: L-D: 10:00-21:00',
    tiposProbioticos: ['Cápsulas', 'Polvos', 'Alimentos fermentados (Kéfir)'],
    marcas: ['Webotanix'],
    precioReferencia: 'Probiotax 150g: €31,95',
    metodosPago: ['Ticket Restaurant®', 'Just Eat', 'Glovo', 'Uber Eats'],
    ventaOnline: true,
    fuente: 'Web oficial, Uber Eats 15',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Muy Alta',
  },
  {
    pais: 'España',
    provincia: 'Comunidad de Madrid',
    ciudad: 'Madrid',
    nombre: 'Salud Mediterránea - Atocha',
    direccion: 'Pso. de Sta. María de la Cabeza 3, 28045 Madrid',
    telefono: '915 278 929, 912 980 909',
    web: 'https://saludmediterranea.com/',
    horarios: 'L-V: 10:00-20:00; S: 10:00-14:00',
    tiposProbioticos: ['Cápsulas'],
    marcas: ['Árbol Verde (marca propia)'],
    precioReferencia: 'Flora 9 (Pro y Prebióticos) 90 Cápsulas: €12.85',
    metodosPago: ['Apple Pay', 'Google Pay', 'Mastercard', 'Shop Pay', 'Visa'],
    ventaOnline: true,
    fuente: 'Web oficial 18',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'España',
    provincia: 'Comunidad de Madrid',
    ciudad: 'Madrid',
    nombre: 'Salud Mediterránea - Manuel Becerra',
    direccion: 'C/ José Ortega y Gasset 77, 28006 Madrid',
    telefono: '913 095 390',
    web: 'https://saludmediterranea.com/',
    horarios: 'L-V: 10:00-20:00; S: 10:00-14:00',
    tiposProbioticos: ['Cápsulas'],
    marcas: ['Árbol Verde (marca propia)'],
    precioReferencia: 'Flora 9 (Pro y Prebióticos) 90 Cápsulas: €12.85',
    metodosPago: ['Apple Pay', 'Google Pay', 'Mastercard', 'Shop Pay', 'Visa'],
    ventaOnline: true,
    fuente: 'Web oficial 20',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'España',
    provincia: 'Cataluña',
    ciudad: 'Barcelona',
    nombre: "Veritas - C.C l'Illa Diagonal",
    direccion: "Av. Diagonal 557 C.C l'Illa Diagonal, 08029 Barcelona",
    telefono: '934 10 15 87',
    web: 'https://veritas.es/',
    horarios: 'L-V: 9:00-20:00; S: 9:00-14:00',
    tiposProbioticos: ['Alimentos fermentados (Kéfir, Kombucha, Chucrut, Tempeh, Miso)'],
    metodosPago: ['Tarjeta de Débito', 'Tarjeta de Crédito'],
    ventaOnline: true,
    fuente: "Web oficial, L'illa Diagonal 9",
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Muy Alta',
  },
  {
    pais: 'España',
    provincia: 'Cataluña',
    ciudad: 'Barcelona',
    nombre: "Herbolario Navarro - Comte d'Urgell",
    direccion: "C/ Comte d'Urgell, 18, 08011 Barcelona",
    telefono: '937 97 83 45',
    web: 'https://www.herbolarionavarro.es/',
    urlProbioticos: 'https://www.herbolarionavarro.es/suplementos-probioticos-y-prebioticos',
    horarios: 'L-V: 9:00-21:00; S: 9:30-21:00',
    tiposProbioticos: ['Cápsulas', 'Sobres', 'Comprimidos'],
    marcas: ['Terra Verda', 'Natures Plus', 'Tongil', 'Nutergia', 'SuraVitasan', 'Bromatech'],
    precioReferencia: 'Megaflora en Sobres (14 uds): €13,99',
    metodosPago: ['Tarjeta de crédito', 'PayPal', 'Transferencia bancaria', 'Bizum'],
    ventaOnline: true,
    fuente: 'Web oficial 1',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'España',
    provincia: 'Cataluña',
    ciudad: 'Barcelona',
    nombre: 'La TRINI Herbolari',
    direccion: 'C/ Lepant, 172, 08013 Barcelona',
    telefono: '932 463 790',
    whatsapp: '+34 615 299 595',
    web: 'http://latrini.cat/',
    horarios: 'L-V: 17:00-20:00; S: 10:00-14:00',
    tiposProbioticos: ['Alimentos fermentados (Kombucha)', 'Suplementos'],
    marcas: ['VITAE', 'A. Vogel', 'Soria Natural'],
    precioReferencia: 'Kombucha VITAE: €4,95',
    ventaOnline: false,
    fuente: 'Eix Fort Pienc, Compra Eixample 25',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Media',
  },
  // México
  {
    pais: 'México',
    provincia: 'Ciudad de México',
    ciudad: 'CDMX',
    nombre: 'Súper Naturista - Ayuntamiento',
    direccion: 'Calle Ayuntamiento No. 14 Loc. 2 y 3, Col. Centro, Cuauhtémoc, 06070 CDMX',
    whatsapp: '55 1113 0305',
    web: 'https://supernaturista.com/',
    urlProbioticos: 'https://supernaturista.com/collections/vitaminas-y-suplementos',
    horarios: 'Varía por sucursal, ej. L-V 09:00-21:00; S 09:00-21:00; D 09:00-21:00',
    tiposProbioticos: ['Cápsulas', 'Comprimidos', 'Polvos'],
    marcas: ['PRONAT', 'VIDANAT', 'YPENZA', 'BIRDMAN'],
    precioReferencia: 'Omega 3 VIDANAT 60 Cap: $188.50 MXN',
    metodosPago: ['Visa', 'MasterCard', 'American Express', 'SPEI', 'PayPal', 'Aplazo', 'OXXO', 'Kueski Pay'],
    ventaOnline: true,
    fuente: 'Rappi, Web oficial 2',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Muy Alta',
  },
  {
    pais: 'México',
    provincia: 'Ciudad de México',
    ciudad: 'CDMX',
    nombre: 'Mercado el 100',
    direccion: 'Plaza del Lanzador, Orizaba S/N, Roma Sur, Cuauhtémoc, 06760 CDMX',
    telefono: '55 3872 6037',
    whatsapp: '+52 55 3872 6037',
    web: 'http://www.mercadoel100.org/',
    horarios: 'Domingos: 9:30-14:30',
    tiposProbioticos: ['Alimentos fermentados', 'quesos artesanales', 'productos de coco y marañón fermentados'],
    marcas: ['Simbiótica', 'Danke Foods', 'Finca Vai-Quesomeliers'],
    ventaOnline: true,
    fuente: 'Web oficial, Instagram 12',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Muy Alta',
  },
  {
    pais: 'México',
    provincia: 'Ciudad de México',
    ciudad: 'CDMX',
    nombre: 'Estado Natural - Condesa',
    direccion: 'Vicente Suárez 85 loc A-B, Condesa, Cuauhtémoc, 06140, CDMX',
    telefono: '(55) 7599 7940',
    web: 'https://estadonatural.com.mx/',
    horarios: 'L-V: 8:30-21:00; S-D: 8:00-20:00',
    tiposProbioticos: ['Alimentos a granel', 'superfoods', 'productos frescos (kombucha, kéfir)'],
    ventaOnline: true,
    fuente: 'Web oficial 30',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'México',
    provincia: 'Ciudad de México',
    ciudad: 'CDMX',
    nombre: 'Aires de Campo',
    direccion: 'Múltiples distribuidores, oficina en: Prolongación Ingenieros Militares 316, San Lorenzo Tlaltenango, Miguel Hidalgo, 11210 CDMX',
    web: 'http://www.airesdecampo.com/',
    tiposProbioticos: ['Abarrotes', 'bebidas', 'carnes', 'lácteos', 'productos frescos (todos orgánicos)'],
    marcas: ['Aires de Campo'],
    ventaOnline: true,
    fuente: 'Web oficial 31',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  // Colombia
  {
    pais: 'Colombia',
    provincia: 'Antioquia',
    ciudad: 'Medellín',
    nombre: 'Tiendas Moli - El Poblado',
    direccion: 'Cr. 32 # 1B Sur-51 Mall Ventura',
    telefono: '(604) 512 74 65',
    whatsapp: '+57 300 439 7900',
    web: 'https://molinatural.com/',
    urlProbioticos: 'https://molinatural.com/categoria-producto/suplementos-dietarios/probioticos/',
    horarios: 'L-V: 8:30-18:00; S: 9:00-16:00',
    tiposProbioticos: ['Cápsulas', 'Gomitas', 'Polvos'],
    marcas: ['Funat', 'Healthy America', 'Natural Systems'],
    precioReferencia: 'Gomitas con probióticos Funat: $36.000 COP',
    ventaOnline: true,
    fuente: 'Web oficial 4',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'Colombia',
    provincia: 'Antioquia',
    ciudad: 'Medellín',
    nombre: 'Sol Verde Tienda Naturista - El Tesoro',
    direccion: 'C.C. El Tesoro, Loma El Tesoro con Transversal Superior, Local 9960',
    telefono: '(604) 418 2009',
    web: 'https://funat.co/nuestras-tiendas/',
    horarios: 'L-S: 8:00-21:30; D y Festivos: 9:00-20:30',
    tiposProbioticos: ['Suplementos', 'vitaminas', 'cosméticos naturales'],
    marcas: ['Funat (marca matriz)'],
    ventaOnline: false,
    fuente: 'Web del centro comercial 34',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'Colombia',
    provincia: 'Antioquia',
    ciudad: 'Medellín',
    nombre: 'Naturista Virtual',
    direccion: 'Online',
    whatsapp: '+57 304 352 8691',
    web: 'https://naturistavirtual.com/',
    horarios: 'Asesoría L-S: 9:00-18:00; Tienda online 24h',
    tiposProbioticos: ['Suplementos dietarios', 'productos fitoterapéuticos'],
    marcas: ['Funat', 'Healthy America', 'Ledmar'],
    precioReferencia: 'Jabón Íntimo Funat: $31.500 COP',
    metodosPago: ['Todos los medios de pago (WOMPI)'],
    ventaOnline: true,
    fuente: 'Web oficial 6',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'Colombia',
    provincia: 'Antioquia',
    ciudad: 'Fredonia',
    nombre: 'Agromandala',
    direccion: 'Cultivo en Fredonia, Antioquia (entrega en Medellín)',
    whatsapp: '+57 320 562 4594',
    web: 'https://www.agromandala.com.co/',
    horarios: 'Entregas los jueves en Medellín',
    tiposProbioticos: ['Alimentos fermentados (Vinagre de plátano maduro)'],
    marcas: ['N/A (productor directo)'],
    precioReferencia: 'Vinagre de Plátano Maduro: desde $22.000 COP',
    ventaOnline: true,
    fuente: 'Web oficial 13',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  // Argentina
  {
    pais: 'Argentina',
    provincia: 'Ciudad Autónoma de Buenos Aires',
    ciudad: 'CABA',
    nombre: 'Dietética Viamonte',
    direccion: 'Viamonte 859, CABA',
    telefono: '011 4322-9380',
    whatsapp: '+54 9 11 4165-4907',
    web: 'https://dieteticaviamonte.com.ar/',
    horarios: 'L-V: 9:00-19:00; S: 9:30-13:00',
    tiposProbioticos: ['Suplementos', 'alimentos naturales'],
    ventaOnline: false,
    fuente: 'Web oficial 5',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
  {
    pais: 'Argentina',
    provincia: 'Ciudad Autónoma de Buenos Aires',
    ciudad: 'CABA',
    nombre: 'Tienda NOVA - Palermo',
    direccion: 'Jerónimo Salguero 1995, Palermo, CABA',
    web: 'https://www.tiendanova.com/',
    urlProbioticos: 'https://www.tiendanova.com/bebidas/kefir/',
    horarios: 'L-S: 8:00-21:00',
    tiposProbioticos: ['Alimentos fermentados (Kéfir, Kombucha, Gaseosa Pre-Probiótica)'],
    ventaOnline: true,
    fuente: 'Web oficial',
    fechaVerificacion: '2024-09-10',
    confiabilidad: 'Alta',
  },
];
