// Base de datos completa basada en la investigación exhaustiva
export const marketData = {
  countries: {
    spain: {
      name: 'España',
      flag: '🇪🇸',
      cities: {
        madrid: {
          name: 'Madrid',
          province: 'Comunidad de Madrid',
          retailers: [
            {
              id: 'es-001',
              name: 'Herbolario Navarro - Fuencarral',
              address: 'C/ Fuencarral, 138, 28010 Madrid',
              phone: '916 227 932',
              whatsapp: null,
              website: 'https://www.herbolarionavarro.es/',
              productUrl: 'https://www.herbolarionavarro.es/suplementos-probioticos-y-prebioticos',
              hours: 'L-V: 9:00-21:00; S: 10:00-21:00; D y Festivos: 11:30-20:30',
              types: ['Cápsulas', 'Sobres', 'Comprimidos'],
              brands: ['Terra Verda', 'Natures Plus', 'Tongil', 'Nutergia', 'SuraVitasan', 'Bromatech'],
              priceExample: 'Megaflora en Sobres (14 uds): €13,99',
              paymentMethods: ['Tarjeta de crédito', 'PayPal', 'Transferencia bancaria', 'Bizum'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'es-002',
              name: 'Ecocentro',
              address: 'C/ Esquilache, 2-12, 28003 Madrid',
              phone: '915 535 502',
              whatsapp: '690 334 737',
              website: 'https://www.ecocentro.es/',
              productUrl: 'https://www.ecocentro.es/tienda/',
              hours: 'Tienda: L-D: 10:00-21:00',
              types: ['Cápsulas', 'Polvos', 'Alimentos fermentados (Kéfir)'],
              brands: ['Webotanix'],
              priceExample: 'Probiotax 150g: €31,95',
              paymentMethods: ['Ticket Restaurant®', 'Just Eat', 'Glovo', 'Uber Eats'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial, Uber Eats',
              verificationDate: '2024-09-10',
              reliability: 'Muy Alta',
              category: 'mercado_local'
            },
            {
              id: 'es-003',
              name: 'Salud Mediterránea - Atocha',
              address: 'Pso. de Sta. María de la Cabeza 3, 28045 Madrid',
              phone: '915 278 929, 912 980 909',
              whatsapp: null,
              website: 'https://saludmediterranea.com/',
              productUrl: 'https://saludmediterranea.com/',
              hours: 'L-V: 10:00-20:00; S: 10:00-14:00',
              types: ['Cápsulas'],
              brands: ['Árbol Verde (marca propia)'],
              priceExample: 'Flora 9 (Pro y Prebióticos) 90 Cápsulas: €12.85',
              paymentMethods: ['Apple Pay', 'Google Pay', 'Mastercard', 'Shop Pay', 'Visa'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'es-004',
              name: 'Salud Mediterránea - Manuel Becerra',
              address: 'C/ José Ortega y Gasset 77, 28006 Madrid',
              phone: '913 095 390',
              whatsapp: null,
              website: 'https://saludmediterranea.com/',
              productUrl: 'https://saludmediterranea.com/',
              hours: 'L-V: 10:00-20:00; S: 10:00-14:00',
              types: ['Cápsulas'],
              brands: ['Árbol Verde (marca propia)'],
              priceExample: 'Flora 9 (Pro y Prebióticos) 90 Cápsulas: €12.85',
              paymentMethods: ['Apple Pay', 'Google Pay', 'Mastercard', 'Shop Pay', 'Visa'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            }
          ]
        },
        barcelona: {
          name: 'Barcelona',
          province: 'Cataluña',
          retailers: [
            {
              id: 'es-005',
              name: 'Veritas - C.C l\'Illa Diagonal',
              address: 'Av. Diagonal 557 C.C l\'Illa Diagonal, 08029 Barcelona',
              phone: '934 10 15 87',
              whatsapp: null,
              website: 'https://veritas.es/',
              productUrl: 'https://veritas.es/',
              hours: 'L-V: 9:00-20:00; S: 9:00-14:00',
              types: ['Alimentos fermentados (Kéfir, Kombucha, Chucrut, Tempeh, Miso)'],
              brands: ['N/D (enfocado en alimentos)'],
              priceExample: null,
              paymentMethods: ['Tarjeta de Débito', 'Tarjeta de Crédito'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial, L\'illa Diagonal',
              verificationDate: '2024-09-10',
              reliability: 'Muy Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'es-006',
              name: 'Herbolario Navarro - Comte d\'Urgell',
              address: 'C/ Comte d\'Urgell, 18, 08011 Barcelona',
              phone: '937 97 83 45',
              whatsapp: null,
              website: 'https://www.herbolarionavarro.es/',
              productUrl: 'https://www.herbolarionavarro.es/suplementos-probioticos-y-prebioticos',
              hours: 'L-V: 9:00-21:00; S: 9:30-21:00',
              types: ['Cápsulas', 'Sobres', 'Comprimidos'],
              brands: ['Terra Verda', 'Natures Plus', 'Tongil', 'Nutergia', 'SuraVitasan', 'Bromatech'],
              priceExample: 'Megaflora en Sobres (14 uds): €13,99',
              paymentMethods: ['Tarjeta de crédito', 'PayPal', 'Transferencia bancaria', 'Bizum'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'es-007',
              name: 'La TRINI Herbolari',
              address: 'C/ Lepant, 172, 08013 Barcelona',
              phone: '932 463 790',
              whatsapp: '+34 615 299 595',
              website: 'http://latrini.cat/',
              productUrl: null,
              hours: 'L-V: 17:00-20:00; S: 10:00-14:00',
              types: ['Alimentos fermentados (Kombucha)', 'Suplementos'],
              brands: ['VITAE', 'A. Vogel', 'Soria Natural'],
              priceExample: 'Kombucha VITAE: €4,95',
              paymentMethods: ['N/D'],
              onlineStore: false,
              delivery: false,
              verificationSource: 'Eix Fort Pienc, Compra Eixample',
              verificationDate: '2024-09-10',
              reliability: 'Media',
              category: 'mercado_local'
            }
          ]
        }
      }
    },
    mexico: {
      name: 'México',
      flag: '🇲🇽',
      cities: {
        cdmx: {
          name: 'Ciudad de México',
          province: 'CDMX',
          retailers: [
            {
              id: 'mx-001',
              name: 'Súper Naturista - Ayuntamiento',
              address: 'Calle Ayuntamiento No. 14 Loc. 2 y 3, Col. Centro, Cuauhtémoc, 06070 CDMX',
              phone: null,
              whatsapp: '55 1113 0305',
              website: 'https://supernaturista.com/',
              productUrl: 'https://supernaturista.com/collections/vitaminas-y-suplementos',
              hours: 'Varía por sucursal, ej. L-V 09:00-21:00; S 09:00-21:00; D 09:00-21:00',
              types: ['Cápsulas', 'Comprimidos', 'Polvos'],
              brands: ['PRONAT', 'VIDANAT', 'YPENZA', 'BIRDMAN'],
              priceExample: 'Omega 3 VIDANAT 60 Cap: $188.50 MXN',
              paymentMethods: ['Visa', 'MasterCard', 'American Express', 'SPEI', 'PayPal', 'Aplazo', 'OXXO', 'Kueski Pay'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Rappi, Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Muy Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'mx-002',
              name: 'Mercado el 100',
              address: 'Plaza del Lanzador, Orizaba S/N, Roma Sur, Cuauhtémoc, 06760 CDMX',
              phone: '55 3872 6037',
              whatsapp: '+52 55 3872 6037',
              website: 'http://www.mercadoel100.org/',
              productUrl: null,
              hours: 'Domingos: 9:30-14:30',
              types: ['Alimentos fermentados (productos de Simbiótica)', 'quesos artesanales', 'productos de coco y marañón fermentados'],
              brands: ['Simbiótica', 'Danke Foods (leches vegetales)', 'Finca Vai-Quesomeliers (lácteos)'],
              priceExample: null,
              paymentMethods: ['Efectivo y tarjetas con cada productor'],
              onlineStore: false,
              delivery: true,
              verificationSource: 'Web oficial, Instagram',
              verificationDate: '2024-09-10',
              reliability: 'Muy Alta',
              category: 'mercado_local'
            },
            {
              id: 'mx-003',
              name: 'Estado Natural - Condesa',
              address: 'Vicente Suárez 85 loc A-B, Condesa, Cuauhtémoc, 06140, CDMX',
              phone: '(55) 7599 7940',
              whatsapp: null,
              website: 'https://estadonatural.com.mx/',
              productUrl: null,
              hours: 'L-V: 8:30-21:00; S-D: 8:00-20:00',
              types: ['Alimentos a granel', 'superfoods', 'productos frescos (kombucha, kéfir)'],
              brands: ['N/D'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'mx-004',
              name: 'Aires de Campo',
              address: 'Prolongación Ingenieros Militares 316, San Lorenzo Tlaltenango, Miguel Hidalgo, 11210 CDMX',
              phone: null,
              whatsapp: null,
              website: 'http://www.airesdecampo.com/',
              productUrl: null,
              hours: 'N/A (distribuidor)',
              types: ['Abarrotes', 'bebidas', 'carnes', 'lácteos', 'productos frescos (todos orgánicos)'],
              brands: ['Aires de Campo (marca propia)'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'especialista_online'
            }
          ]
        }
      }
    },
    colombia: {
      name: 'Colombia',
      flag: '🇨🇴',
      cities: {
        medellin: {
          name: 'Medellín',
          province: 'Antioquia',
          retailers: [
            {
              id: 'co-001',
              name: 'Tiendas Moli - El Poblado',
              address: 'Cr. 32 # 1B Sur-51 Mall Ventura',
              phone: '(604) 512 74 65',
              whatsapp: '+57 300 439 7900',
              website: 'https://molinatural.com/',
              productUrl: 'https://molinatural.com/categoria-producto/suplementos-dietarios/probioticos/',
              hours: 'L-V: 8:30-18:00; S: 9:00-16:00',
              types: ['Cápsulas', 'Gomitas', 'Polvos'],
              brands: ['Funat', 'Healthy America', 'Natural Systems'],
              priceExample: 'Gomitas con probióticos Funat: $36.000 COP',
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'co-002',
              name: 'Sol Verde Tienda Naturista - El Tesoro',
              address: 'C.C. El Tesoro, Loma El Tesoro con Transversal Superior, Local 9960',
              phone: '(604) 418 2009',
              whatsapp: null,
              website: 'https://funat.co/nuestras-tiendas/',
              productUrl: null,
              hours: 'L-S: 8:00-21:30; D y Festivos: 9:00-20:30',
              types: ['Suplementos', 'vitaminas', 'cosméticos naturales'],
              brands: ['Funat (marca matriz) y otras'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: false,
              delivery: false,
              verificationSource: 'Web del centro comercial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'co-003',
              name: 'Naturista Virtual',
              address: 'Online',
              phone: null,
              whatsapp: '+57 304 352 8691',
              website: 'https://naturistavirtual.com/',
              productUrl: null,
              hours: 'Asesoría L-S: 9:00-18:00; Tienda online 24h',
              types: ['Suplementos dietarios', 'productos fitoterapéuticos'],
              brands: ['Funat', 'Healthy America', 'Ledmar'],
              priceExample: 'Jabón Íntimo Funat: $31.500 COP',
              paymentMethods: ['Todos los medios de pago (WOMPI)'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'especialista_online'
            }
          ]
        },
        fredonia: {
          name: 'Fredonia',
          province: 'Antioquia',
          retailers: [
            {
              id: 'co-004',
              name: 'Agromandala',
              address: 'Cultivo en Fredonia, Antioquia (entrega en Medellín)',
              phone: null,
              whatsapp: '+57 320 562 4594',
              website: 'https://www.agromandala.com.co/',
              productUrl: null,
              hours: 'Entregas los jueves en Medellín',
              types: ['Alimentos fermentados (Vinagre de plátano maduro)'],
              brands: ['N/A (productor directo)'],
              priceExample: 'Vinagre de Plátano Maduro: desde $22.000 COP',
              paymentMethods: ['N/D'],
              onlineStore: false,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'mercado_local'
            }
          ]
        }
      }
    },
    argentina: {
      name: 'Argentina',
      flag: '🇦🇷',
      cities: {
        buenosaires: {
          name: 'Buenos Aires',
          province: 'Ciudad Autónoma de Buenos Aires',
          retailers: [
            {
              id: 'ar-001',
              name: 'Dietética Viamonte',
              address: 'Viamonte 859, CABA',
              phone: '011 4322-9380',
              whatsapp: '+54 9 11 4165-4907',
              website: 'https://dieteticaviamonte.com.ar/',
              productUrl: null,
              hours: 'L-V: 9:00-19:00; S: 9:30-13:00',
              types: ['Suplementos', 'alimentos naturales'],
              brands: ['N/D'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: false,
              delivery: false,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'mercado_local'
            },
            {
              id: 'ar-002',
              name: 'Tienda NOVA - Palermo',
              address: 'Jerónimo Salguero 1995, Palermo, CABA',
              phone: null,
              whatsapp: null,
              website: 'https://www.tiendanova.com/',
              productUrl: 'https://www.tiendanova.com/bebidas/kefir/',
              hours: 'L-S: 8:00-21:00',
              types: ['Alimentos fermentados (Kéfir, Kombucha, Gaseosa Pre-Probiótica)'],
              brands: ['Cocoon'],
              priceExample: 'Gaseosa Pre-Probiótica Cocoon 354ml: $2.700 ARS',
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Muy Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'ar-003',
              name: 'Biomarket',
              address: 'Av. Pueyrredón 2088, Recoleta, CABA',
              phone: '11 6472-5536',
              whatsapp: null,
              website: 'https://biomarket.com.ar/',
              productUrl: 'https://biomarket.com.ar/product-category/veganos/fermentos_probioticos/',
              hours: 'N/D',
              types: ['Fermentos Probióticos'],
              brands: ['N/D'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial, Instagram',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'ar-004',
              name: 'El Galpón - Centro Comunal de Abastecimiento',
              address: 'Av. Federico Lacroze 4171, Chacarita, CABA',
              phone: null,
              whatsapp: null,
              website: 'https://elgalpon.org.ar/',
              productUrl: null,
              hours: 'Miércoles y Sábados: 9:00-18:00',
              types: ['Alimentos y bebidas naturales', 'productos orgánicos y agroecológicos'],
              brands: ['Doctor Mate', 'Panalivia (marcas de productores asociados)'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: false,
              delivery: false,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'mercado_local'
            }
          ]
        }
      }
    },
    chile: {
      name: 'Chile',
      flag: '🇨🇱',
      cities: {
        santiago: {
          name: 'Santiago',
          province: 'Región Metropolitana',
          retailers: [
            {
              id: 'cl-001',
              name: 'Tienda Natural by BowSPA',
              address: 'Las Tranqueras 1250, Vitacura, Santiago',
              phone: null,
              whatsapp: '+56 9 9802 9416',
              website: 'https://tiendanatural.cl/',
              productUrl: 'https://tiendanatural.cl/categoria-producto/suplementos-y-alimentos/',
              hours: 'N/D',
              types: ['Suplementos', 'alimentos naturales', 'fitocosmética'],
              brands: ['N/D'],
              priceExample: 'Jalea Real: $16.500 CLP',
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'especialista_online'
            },
            {
              id: 'cl-002',
              name: 'Farmacia Mapuche Makelawen',
              address: 'Múltiples sucursales',
              phone: '(+56) 2 2406 3700',
              whatsapp: null,
              website: 'https://farmaciamapuche.cl/',
              productUrl: 'https://farmaciamapuche.cl/suplementos-y-alimentos/probioticos',
              hours: 'N/D',
              types: ['Cápsulas', 'Comprimidos masticables', 'Vinagres'],
              brands: ['HERBOANDINA', 'MANARE', 'DISTRIBUCION NATURAL', 'EMPROQUIM'],
              priceExample: 'PROBIONAT + PREBIÓTICO 60 cápsulas: $12.990 CLP',
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Muy Alta',
              category: 'cadena_nacional'
            },
            {
              id: 'cl-003',
              name: 'Mercado Drugstore',
              address: 'Av. Providencia 2124, pasaje Las Urbinas, Providencia, Santiago',
              phone: null,
              whatsapp: null,
              website: 'https://www.mercadodrugstore.cl/',
              productUrl: null,
              hours: 'Sábados',
              types: ['Productos orgánicos', 'sostenibles', 'de emprendedores locales'],
              brands: ['N/A'],
              priceExample: null,
              paymentMethods: ['N/D'],
              onlineStore: false,
              delivery: false,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'mercado_local'
            },
            {
              id: 'cl-004',
              name: 'Probiotico.cl',
              address: 'Online',
              phone: '+56 2 2266 4996',
              whatsapp: null,
              website: 'https://probiotico.cl/',
              productUrl: 'https://probiotico.cl/',
              hours: 'L-V: 9:00-18:00 (atención telefónica)',
              types: ['Cápsulas'],
              brands: ['Probioseries (marca propia)'],
              priceExample: 'Probioseries Digestive 25 Billones (30 cápsulas): $6.990 CLP (oferta)',
              paymentMethods: ['N/D'],
              onlineStore: true,
              delivery: true,
              verificationSource: 'Web oficial',
              verificationDate: '2024-09-10',
              reliability: 'Alta',
              category: 'especialista_online'
            }
          ]
        }
      }
    }
  }
};

export const categoryLabels = {
  cadena_nacional: 'Cadena Nacional',
  especialista_online: 'Especialista Online',
  mercado_local: 'Mercado Local'
};

export const categoryIcons = {
  cadena_nacional: '🏪',
  especialista_online: '💻',
  mercado_local: '🌱'
};
